name: Prod Deploy to SSH Server

on:
  push:
    branches:
      - main # Change this to your main branch
# on:
#   workflow_dispatch:
#     inputs:
#       branch:
#         description: 'Branch to deploy'
#         required: true
#         default: 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'
      #     check-latest: true
      #     cache: 'yarn'
      # - name: Install dependencies
      #   run: yarn install

      # - name: Build Next.js app
      #   run: yarn run build

      - name: Deploy to SSH server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          script: |
            cd ~/apps/rang/prod/rangurura-app
            git stash
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm  install
            npm  run build
            pm2 restart rangurura-app
